### ISSUE TITLE
Angular 8.2.12

### ISSUE THREAD

**Issue by adr75** [visjs/ngx-vis#407]
Hello, 
Can you confirm that it is supposed to work with Angular 8.2.12?

When I try to build the app after adding the ngx-vis package, and copy pasting the code from timeline demo, I got a lot of errors:

`ERROR in ../node_modules/vis-network/declarations/index-legacy.d.ts:13:23 - error TS2307: Cannot find module 'vis-util/esnext'.

13 import * as util from "vis-util/esnext";
                         ~~~~~~~~~~~~~~~~~
../node_modules/vis-network/declarations/index-legacy.d.ts:15:23 - error TS2307: Cannot find module 'vis-data/esnext'.

15 import * as data from "vis-data/esnext";
                         ~~~~~~~~~~~~~~~~~
../node_modules/vis-network/declarations/index-legacy.d.ts:17:42 - error TS2307: Cannot find module 'vis-data/esnext'.

17 export { DataSet, DataView, Queue } from "vis-data/esnext";
                                            ~~~~~~~~~~~~~~~~~
../node_modules/vis-network/declarations/index-legacy.d.ts:18:25 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

18 import * as moment from "./module/moment";
                           ~~~~~~~~~~~~~~~~~
../node_modules/vis-network/declarations/index-legacy.d.ts:20:25 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

20 import * as Hammer from "./module/hammer";
                           ~~~~~~~~~~~~~~~~~
../node_modules/vis-network/declarations/index-legacy.d.ts:22:27 - error TS2307: Cannot find module 'keycharm'.

22 import * as keycharm from "keycharm";
                             ~~~~~~~~~~
../node_modules/vis-network/declarations/module/hammer.d.ts:1:20 - error TS2307: Cannot find module '@egjs/hammerjs'.

1 import hammer from '@egjs/hammerjs'
                     ~~~~~~~~~~~~~~~~
../node_modules/vis-network/declarations/module/moment.d.ts:1:20 - error TS2307: Cannot find module 'moment'.

1 import moment from 'moment'
                     ~~~~~~~~
../node_modules/vis-network/declarations/network/Network.d.ts:19:50 - error TS2307: Cannot find module 'vis-data'.

19 import { DataInterface, DataSet, DataView } from 'vis-data';
                                                    ~~~~~~~~~~
../node_modules/vis-timeline/declarations/index.d.ts:19:50 - error TS2307: Cannot find module 'vis-data'.

19 import { DataInterface, DataSet, DataView } from 'vis-data';
                                                    ~~~~~~~~~~
../node_modules/vis-timeline/declarations/index.d.ts:27:64 - error TS2307: Cannot find module 'moment'.

27 import { MomentInput, MomentFormatSpecification, Moment } from 'moment';
                                                                  ~~~~~~~~`

When I try to install the missing module, I got this:

`../node_modules/vis-network/declarations/index-legacy.d.ts:20:25 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.`

Thanks!
Adrien

**Comment by hypery2k** [comment]
can you post your package.json?

**Comment by keforbes** [comment]
I'm seeing the exact same error as above.  However, if I downgrade to `ngx-vis: 3.0.2` everything works fine.  Also, I already have `allowSyntheticDefaultImports` set in my tsconfig.json and that error still shows up in ngx-vis 3.0.3+.

**Comment by adr75** [comment]
> can you post your package.json?

Here it is: [package.json.txt](https://github.com/visjs/ngx-vis/files/5160604/package.json.txt)

**Comment by willredington** [comment]
thanks to @keforbes, downgrading to v3.0.2 works for Angular 10

**Comment by hypery2k** [comment]
could you give `ngx-vis@3.1.0-build1603138697` a try?

**Comment by keforbes** [comment]
Using build `ngx-vis@3.1.0-build1603138697` I'm getting the following error:
```
WARNING in Entry point 'ngx-vis' contains deep imports into '/my_project/node_modules/vis-network/esnext', '/my_project/node_modules/vis-timeline/esnext'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

ERROR in The target entry-point "ngx-vis" has missing dependencies:
 - vis-data/esnext
```

**Comment by edson7th** [comment]
I have the same problem

**Comment by mogudy** [comment]
Angular 11, downgraded to 3.0.2 and still need to modify types files in node_modules/vis_timeline and node_modules/vis_network.

Need to replace 

`import Hammer from 'hammerjs'` with `import * as Hammer from 'hammerjs' `

and 

`import moment from 'moment'` with `import * as moment from 'moment' `

**Comment by hypery2k** [comment]
you can give "ngx-vis@3.1.0-build1627370228" a try

**Comment by mogudy** [comment]
> you can give "ngx-vis@3.1.0-build1627370228" a try

esnext no longer breaks compilation, now keycharm does.

btw. esModuleInterop & allowSyntheticDefaultImports are still mandatory.

 node_modules/vis-network/declarations/index-legacy.d.ts:22:27 - error TS7016: Could not find a declaration file for module 'keycharm'.

**Comment by hypery2k** [comment]
did you installed the peer dependencies?
Can you post your package.json?

**Comment by BhagyashriJ** [comment]
Any solution for this ? Its also failing for angular 13 in build phase with 3.0.2

**Comment by hypery2k** [comment]
a new preview is available via `npm i ngx-vis@next`

Otherwise track issues please here #457
